### PR TITLE
fixed context menu issue #714

### LINKED ISSUE #714: Context menu gets cut off when cursor is near the bottom of the screen
**Describe the bug**
When the cursor is near the bottom of the screen and the user right clicks, the context menu will simply appear in a position that cuts off the bottom portion of it.

**To Reproduce**
1. Go to https://nightly.opencircuits.io/
2. Move the cursor near the bottom of the screen
3. Right click and observe the context menu being cut off

**Expected behavior**
When the normal behavior would result in the context menu being cut off, I would expect the context menu to either:
 - appear with the bottom left corner at the position of the cursor, rather than the top left
 - appear with only the left edge at the cursor's position, but the vertical position simply as close to the bottom of the screen as it can get (less a slight gap for readability)

**Screenshots**
My cursor is invisible in the screenshots, but pretend it's in the same spot each time (top left corner of the context menu in the first screenshot)

Current behavior:
Screenshot (40)

Expected behavior option 1:
Screenshot (41)

Expected behavior option 2:
Screenshot (42)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

### PR DESCRIPTION
**Pull request by Kevin-771**
made it so that if the context menu were to go offscreen, it would be created on the opposite side of the cursor.

closes #714

### CODE REVIEW

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 1]
```diff
@@ -15,6 +15,7 @@ import {useHistory} from "shared/utils/hooks/useHistory";
 
 
 import "./index.scss";
+import { HEADER_HEIGHT } from "shared/utils/Constants";
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:18]: nit: Remove spaces inside `{}`

Comment (LeonMontealegre) [reply src/site/shared/containers/ContextMenu/index.tsx:18]: nit: Move constants to be the top import under import from "react"

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 2]
```diff
@@ -24,6 +25,8 @@ function isClipboardSupported(type: "read" | "write"): boolean {
 }
 
 
+const CONTEXT_MENU_OFFSET = 4;
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:28]: What does this represent? Add a comment?

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]
This doesn't appear to fix the issue as far as I can tell, it still appears to go off screen

**Review by LeonMontealegre — APPROVED** [review]
