### PR TITLE
Copy from component popup

### LINKED ISSUE #874: Copy pasting text from a component's selection popup pastes the entire component
**Describe the bug**
When copying a field from a selection popup (such as the position, delay, or component name), if the user attempts to paste the information into another input field the site will act as if the user was just copy pasting the component, not the text.

**To Reproduce**
1. Add two labels to the canvas
2. Give one label a new name ("Input", for example)
3. Highlight the label's new name in the selection popup, and copy it
4. Attempt to paste the name into the other label's name field
5. observe error

**Expected behavior**
I would expect that when text is highlighted by the user, nothing but that text is copied to the clipboard.

**Screenshots**
A gif showing an example of this happening (the same example as described above):
animation

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
When doing the original copying from somewhere else (some other tab), the pasting works fine. It appears that this bug is entirely an issue with copying, not with pasting.

### PR DESCRIPTION
**Pull request by riedee**
Resolves #874

If any text is selected within a component's popup, it will copy the text instead of the entire component as it did previously.
If the cursor is in the text field but nothing is selected, it will copy the component. I thought this made the most sense, but that can be changed easily if not.

### CODE REVIEW

File: src/app/core/tools/handlers/CopyHandler.ts [hunk 1]
```diff
@@ -27,7 +27,12 @@ export const CopyHandler: EventHandler = ({
         // We don't copy the data from the json since it will cause 
         // some weird error, which will cause the issue #746
         ev.clipboardData.setData("text/plain", str);
-        ev.preventDefault(); // Necessary to copy correctly
+
+        // If no text is selected, copy the component
+        // Otherwise, do default copying
```
Comment (LeonMontealegre) [inline src/app/core/tools/handlers/CopyHandler.ts:32]: Can you expand this comment to explain what exactly this if-statement is doing?
I'm not sure what the `'LABEL'` thing represents, or why the `"CARET"` matters?

Also, you should say (in the comment) that this statement is necessary because it "fixes #874"

File: src/app/core/tools/handlers/CopyHandler.ts [hunk 2]
```diff
@@ -27,7 +27,12 @@ export const CopyHandler: EventHandler = ({
...
+        if (document.getSelection()?.anchorNode?.nodeName != 'LABEL' || document.getSelection()?.type == "Caret") {
```
Comment (LeonMontealegre) [inline src/app/core/tools/handlers/CopyHandler.ts:33]: nit: use `!==`
nit: use `"` instead of `'` for strings
nit: use `===`

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]

File: src/app/core/tools/handlers/CopyHandler.ts (hunk 1 above)
Comment (riedee) [reply src/app/core/tools/handlers/CopyHandler.ts]: Yeah that definitely wasn't clear, hopefully the comments I added make it more understandable.

File: src/app/core/tools/handlers/CopyHandler.ts [hunk 3]
```diff
@@ -27,7 +27,15 @@ export const CopyHandler: EventHandler = ({
         // We don't copy the data from the json since it will cause 
         // some weird error, which will cause the issue #746
         ev.clipboardData.setData("text/plain", str);
-        ev.preventDefault(); // Necessary to copy correctly
+
+        // If an editable component (LABEL) is not selected, 
+        // or if an editable component is selected but it is a "Caret" (cursor) instead of highlighted text,
```
Comment (LeonMontealegre) [inline src/app/core/tools/handlers/CopyHandler.ts:32]: Definitely clearer, but where exactly did you get the string `"LABEL"`, why is it in all caps? I've never seen it before so I'm more just wondering.

Comment (riedee) [reply src/app/core/tools/handlers/CopyHandler.ts:32]: Basically I noticed that all the input elements in the popup modules had that anchor node name. I believe it's because in Module.tsx there's this section for the popup module:
```
export const PopupModule = (({label, modules}: PopupModuleProps) => {
    return function PopupModuleFunc (props: UseModuleProps) {
        const ms = modules.map(m => m(props));
        if (ms.every(m => m === null))
            return null;
        return <div key={`selection-popup-${label}-module`}>
            {label}
            <label unselectable="on">
                {ms.map((m, i) => cloneElement(m!, {key: `selection-popup-${label}-module-${i}`}))}
            </label>
        </div>;
    }
});
```
Each of the inputs seems to be surrounded by a label element, which is why when my cursor is in an input and I call the anchor node name, it returns label. I'm not sure why it's in all caps, but it seems to be the same for all other types of node names as well (I'm assuming it's just an HTML thing?).

**Review by LeonMontealegre — APPROVED** [review]
