### PR TITLE
Fixed issue 774

### LINKED ISSUE #774: When splitting a colored wire, the resulting two wires are both uncolored
**Describe the bug**
When splitting a wire the two halves of the wire on either side of the new port will be created colored white, whereas they should be the color of the original (pre-split) wire.

**To Reproduce**
1. place any two connectable components on the canvas, and connect them with a wire
2. color the wire some color other than white
3. Split the wire
4. Observe the two halves of the split wire being white, rather than the other color

**Expected behavior**
I would expect the wire to split into two pieces that share the color of the initial wire.

**Screenshots**
Example circuit with colored wire:
Screenshot (67)

Current outcome when splitting wire:
Screenshot (68)

Expected outcome when splitting wire:
Screenshot (69)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome

### PR DESCRIPTION
**Pull request by vhada7**
Fixed the issue of the color of the wires changing when split. Now the color stays the same by making the color of the new split wires equal to the previous wires color in the file SplitWireAction.ts.

Closes #774

### CODE REVIEW

File: src/app/core/actions/addition/SplitWireAction.ts [hunk 1]
```diff
@@ -8,13 +8,22 @@ import {ConnectionAction, DisconnectAction} from "./ConnectionAction";
 import {PlaceAction, DeleteAction} from "./PlaceAction";
 
 
+
```
Comment (LeonMontealegre) [inline src/app/core/actions/addition/SplitWireAction.ts:11]: nit: delete extra line

File: src/app/core/actions/addition/SplitWireAction.ts [hunk 2]
```diff
@@ -8,13 +8,22 @@ import {ConnectionAction, DisconnectAction} from "./ConnectionAction";
...
 export function CreateSplitWireAction(designer: CircuitDesigner, w: Wire, port: Node): GroupAction {
     const action = new GroupAction();
-
+
```
Comment (LeonMontealegre) [inline src/app/core/actions/addition/SplitWireAction.ts:14]: nit: delete extra space

File: src/app/core/actions/addition/SplitWireAction.ts [hunk 3]
```diff
@@ -8,13 +8,22 @@ import {ConnectionAction, DisconnectAction} from "./ConnectionAction";
...
 export function CreateSplitWireAction(designer: CircuitDesigner, w: Wire, port: Node): GroupAction {
     const action = new GroupAction();
-
+    
     action.add(new DisconnectAction(designer, w).execute());
     action.add(new PlaceAction(designer, port).execute());
-    action.add(new ConnectionAction(designer, w.getP1(), port.getP1()).execute());
-    action.add(new ConnectionAction(designer, port.getP2(), w.getP2()).execute());
+    //creates and saves new ConnectionAction to a var and then executes the action.
```
Comment (LeonMontealegre) [inline src/app/core/actions/addition/SplitWireAction.ts:17]: nit: put extra line above this
nit: space after `//`
nit: capitalize first letter of comment

File: src/app/core/actions/addition/SplitWireAction.ts [hunk 4]
```diff
@@ -8,13 +8,22 @@ import {ConnectionAction, DisconnectAction} from "./ConnectionAction";
...
+    const con1 = new ConnectionAction(designer, w.getP1(), port.getP1());
+    action.add(con1.execute());
+    //After execution the color of the first half of the new wire is set to the color of the old wire.
```
Comment (LeonMontealegre) [inline src/app/core/actions/addition/SplitWireAction.ts:20]: nit: space after `//`

File: src/app/core/actions/addition/SplitWireAction.ts [hunk 5]
```diff
@@ -8,13 +8,22 @@ import {ConnectionAction, DisconnectAction} from "./ConnectionAction";
...
+    con1.getWire().setColor(w.getColor());
+
+    //repeats same process for the other half of the split wire.
```
Comment (LeonMontealegre) [inline src/app/core/actions/addition/SplitWireAction.ts:23]: nit: space after `//`
nit: capitalize first letter of comment

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]

**Review by LeonMontealegre — APPROVED** [review]
