### PR TITLE
Example circuit fix

### LINKED ISSUE #599: Example Circuits broken
**Describe the bug**
When clicking one of the example circuits to place it, the example circuit is not placed, and this sometime results in an error.

**To Reproduce**
1. Go to the latest version of the master branch
2. Click on the three line button in the top left
3. Click on any of the examples, then click ok to overwrite the scene
4. On Chrome on Windows, the circuits are not placed
5. On safari on iPhone 6s plus, an error is given for the AND gate and S-R Latch (screenshot below)

**Expected behavior**
The example circuit is placed 

**Screenshots**
IMG_4464

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: iPhone 6s plus
 - OS: iOS 14.4
 - Browser safari

### PR DESCRIPTION
**Pull request by JumpingKangaroo**
This fixes #599. It attaches a callback to every time an example circuit is requested, that runs the circuit through the `VersionConflictResolver`. If the version is up to date, then `VersionConflictResolver` is a no op. 

I'm able to load into the example circuits as normal, edit them, and then save them to my personal save collection.

### CODE REVIEW

File: src/site/shared/containers/SideNav/index.tsx [hunk 1]
```diff
@@ -23,7 +25,11 @@ function LoadExampleCircuit(data: CircuitMetadata): Promise<string> {
         method: "GET",
         url: `/examples/${data.getId()}`,
         headers: {}
-    });
+    })
+    // We want to run example circuits through the VersionConflictResolver to make sure they're up to date.
+    .then(
+        (circuitJson) => VersionConflictResolver(circuitJson)
+    );
```
Comment (LeonMontealegre) [inline src/site/shared/containers/SideNav/index.tsx:32]: This can be compressed down to just `.then(VersionConflictResolver)`

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]
Great job! But I think in part we should actually update the example circuits to be the most recent version, could you update them as part of this PR? You just gotta load them and save them using the Download file functionality and then replace the file in `examples`

**Comment by JumpingKangaroo** [comment]
Made the changes! To test that the example circuits were updated correctly, I commented out the `.then(VersionConflictResolver)` and then verified that I could open the example circuits.

**Review by LeonMontealegre — APPROVED** [review]
