### PR TITLE
ContextMenu Improvement

### LINKED ISSUE #914: context menu is relocated when performing certain actions
**Describe the bug**
The context menu is relocated when:
1. opening/closing the itemnav
2. placing a component on the canvas from the itemnav
3. opening the sidenav
4. locking/unlocking the canvas
5. clicking the sign-in button, utilities button, download button, open file button, settings button, and help button
Those are the actions that I have found so far

**To Reproduce**
1. Go to https://nightly.opencircuits.io/
2. Right-click on canvas to create context menu
3. Reproduce any of the above actions
4. See that the context menu is moved

**Expected behavior**
The expected behavior is either that the context menu closes or it does not move. At the moment, it does neither.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I think it is the same cause as issue #822. Something about having to redraw the canvas moves the context menu, I think

### PR DESCRIPTION
**Pull request by Cyphecx**
fixes #914 

Addressing the issue that the context menu jumps around when certain updates occur, such as clicking on the settings button.
The menu now closes instead, when an update occurs.
Before:
notworking
After:
working

### CODE REVIEW

**Review by TGCrystal — APPROVED** [review]

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 1]
```diff
@@ -55,7 +58,47 @@ export const ContextMenu = ({info, paste}: Props) => {
...
                 dispatch(CloseContextMenu());
         });
-    }, [input])
+    }, [input]);
+
+    /*Position changes are calculated using the react hook so that the
+     *context menu does not jump around during other update events.
+    */
+    useEffect(() => {
+        if(isOpen){
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:67]: Change this to a 
```ts
if (!isOpen)
    return;
```
and then de-indent the rest of the code by 1

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 2]
```diff
@@ -34,17 +35,19 @@ type Props = {
...
 
-    const {isOpen} = useSharedSelector(
+    const { isOpen } = useSharedSelector(
         state => ({ isOpen: state.contextMenu.isOpen })
     );
     const dispatch = useSharedDispatch();
 
     let menuPos: Vector;
 
+    const [{ posX,posY }, setPos] = useState({ posX:0,posY:0 });
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:49]: nit: space between `posX` and `posY` after comma in both places

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 3]
```diff
@@ -55,7 +58,47 @@ export const ContextMenu = ({info, paste}: Props) => {
             else if (ev.type === "mousedown")
                 dispatch(CloseContextMenu());
         });
-    }, [input])
+    }, [input]);
+
+    /*Position changes are calculated using the react hook so that the
+     *context menu does not jump around during other update events.
+    */
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:65]: nit: use `//` for non-JSDoc comments
nit: link the issue for reference like ("`necessary to fix #914`")

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 4]
```diff
@@ -55,7 +58,47 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+
+            if (!menu.current)
+                throw new Error("ContextMenu failed: menu.current is null");
+
+            const offset = 1;
+            const contextMenuWidth = menu.current.getBoundingClientRect().width;
+            const contextMenuHeight = menu.current.getBoundingClientRect().height;
+
+
+            if (pos.x+ contextMenuWidth > window.innerWidth)
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:78]: nit: space before the `+`

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 5]
```diff
@@ -55,7 +58,47 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+
+    useDocEvent("mousedown", (ev) => {
+        if (!menu.current)
+            throw new Error("ContextMenu failed: menu.current is null");
+
+        const contextMenuWidth = menu.current.getBoundingClientRect().width;
+        const contextMenuHeight = menu.current.getBoundingClientRect().height;
+
+        if(ev.clientX < posX || ev.clientX > (posX + contextMenuWidth) ||  ev.clientY < posY || ev.clientY > (posY + contextMenuHeight))
+            dispatch(CloseContextMenu());
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:100]: I believe you're checking if the mouse position the user clicked is within the bounds of the menu?
If so, I think a much easier way to do this is just check if `menu.current.contains(ev.target)`

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 6]
```diff
@@ -55,7 +58,47 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+                pos.x -= contextMenuWidth - offset;
+
+            if (pos.y + contextMenuHeight + HEADER_HEIGHT - CONTEXT_MENU_VERT_OFFSET > window.innerHeight)
+                pos.y -= contextMenuHeight - offset;
+
+            //updates position state
+            setPos({ posX:pos.x, posY:pos.y });
+
+            // Update context menu position on canvas
+            menuPos = camera.getWorldPos(input.getMousePos());
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:88]: I had to re-remember why this was even necessary, I think it's because the position to `paste` at isn't necessarily the context menu position since if the user clicks near the edge of the screen, the context menu gets moved slightly away.

But anyways, unfortunately, this should also be converted to a state variable and updated accordingly, but let's rename it like `pastePos` (`pastePosX`, `pastePosY`)

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 7]
```diff
@@ -55,7 +56,28 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+    }, [input]);
+
+    // Position changes are calculated using the react hook so that the
+    // context menu does not jump around during other update events.
+    // fixes issue #914
+    useEffect(() => {
+        if (!isOpen)
+            return;
+        // Updates position state
+        let pos = input?.getMousePos();
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:68]: nit: use `const`

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 8]
```diff
@@ -55,7 +56,28 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+        setPos({ posX:pos.x, posY:pos.y });
+
+
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:71]: nit: remove unnecessary lines

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 9]
```diff
@@ -55,7 +56,28 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+    }, [isOpen]);
+
+    useDocEvent("mousedown", (ev) => {
+        if (!menu.current)
+            throw new Error("ContextMenu failed: menu.current is null");
+
+        if (!menu.current.contains(ev.target as Node))
+            dispatch(CloseContextMenu());
+    });
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:80]: add blank (`[]`) dependency list to this `useDocEvent` otherwise, it'll add some overhead

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 10]
```diff
@@ -118,33 +140,30 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+
     const menu = useRef<HTMLDivElement>(null);
-    let pos = input?.getMousePos();
 
-    /* Relocate context menu to opposite side of cursor if it were to go off-screen */
-    if (isOpen) {
-        if (!menu.current)
-            throw new Error("ContextMenu failed: menu.current is null");
+    // Adjusts position of menu to keep it on screen
+    let pos = V(posX, posY);
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:147]: Call this like `menuPos` or something, also it can be `const` since the variable itself isn't changing

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 11]
```diff
@@ -118,33 +140,30 @@ export const ContextMenu = ({info, paste}: Props) => {
...
+    if(menu.current){
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:148]: nit: space after `if` and before `{`

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 12]
```diff
@@ -118,33 +140,30 @@ export const ContextMenu = ({info, paste}: Props) => {
...
         const offset = 1;
         const contextMenuWidth = menu.current.getBoundingClientRect().width;
         const contextMenuHeight = menu.current.getBoundingClientRect().height;
 
+
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:153]: nit: remove extra line

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 13]
```diff
@@ -118,33 +140,30 @@ export const ContextMenu = ({info, paste}: Props) => {
...
-    /* Relocate context menu to opposite side of cursor if it were to go off-screen */
-    if (isOpen) {
-        if (!menu.current)
-            throw new Error("ContextMenu failed: menu.current is null");
+    // Adjusts position of menu to keep it on screen
+    let pos = V(posX, posY);
+    if(menu.current){
         const offset = 1;
         const contextMenuWidth = menu.current.getBoundingClientRect().width;
         const contextMenuHeight = menu.current.getBoundingClientRect().height;
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:151]: I know you didn't write this, but we can simplify this to:
```ts
const {width, height} = menu.current.getBoundingClientRect();
```
i believe (and then change the if-statements below to use `width`,`height` instead

File: src/site/shared/containers/ContextMenu/index.tsx [hunk 14]
```diff
@@ -155,5 +174,5 @@ export const ContextMenu = ({info, paste}: Props) => {
             <button title="Undo" onClick={() => doFunc(onUndo)} disabled={undoHistory.length === 0}>Undo</button>
             <button title="Redo" onClick={() => doFunc(onRedo)} disabled={redoHistory.length === 0}>Redo</button>
         </div>
-    );
+   );
```
Comment (LeonMontealegre) [inline src/site/shared/containers/ContextMenu/index.tsx:177]: change spacing back to 4-spaces here

**Review by LeonMontealegre — CHANGES_REQUESTED** [review]

**Review by TGCrystal — APPROVED** [review]

**Review by LeonMontealegre — APPROVED** [review]
